game_data = [
    {"name": "Elon Musk", "score": 240, "profession": "Entrepreneur", "country": "South Africa"},
    {"name": "Taylor Swift", "score": 200, "profession": "Singer-Songwriter", "country": "United States"},
    {"name": "Cristiano Ronaldo", "score": 500, "profession": "Footballer", "country": "Portugal"},
    {"name": "MrBeast", "score": 175, "profession": "YouTuber", "country": "United States"},
    {"name": "Oprah Winfrey", "score": 280, "profession": "TV Host", "country": "United States"},
    {"name": "Mark Zuckerberg", "score": 110, "profession": "Tech CEO", "country": "United States"},
    {"name": "Beyoncé", "score": 180, "profession": "Singer & Actress", "country": "United States"},
    {"name": "Dwayne Johnson", "score": 270, "profession": "Actor & Wrestler", "country": "United States"},
    {"name": "Jeff Bezos", "score": 190, "profession": "Entrepreneur", "country": "United States"},
    {"name": "Bill Gates", "score": 125, "profession": "Tech Philanthropist", "country": "United States"},
    {"name": "Ariana Grande", "score": 160, "profession": "Singer & Actress", "country": "United States"},
    {"name": "Lionel Messi", "score": 470, "profession": "Footballer", "country": "Argentina"},
    {"name": "Emma Watson", "score": 130, "profession": "Actress", "country": "United Kingdom"},
    {"name": "Narendra Modi", "score": 150, "profession": "Prime Minister", "country": "India"},
    {"name": "PewDiePie", "score": 145, "profession": "YouTuber", "country": "Sweden"},
    {"name": "BLACKPINK", "score": 210, "profession": "K-Pop Group", "country": "South Korea"},
    {"name": "Rihanna", "score": 215, "profession": "Singer & Entrepreneur", "country": "Barbados"},
    {"name": "LeBron James", "score": 300, "profession": "Basketball Player", "country": "United States"},
]